# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(choices=[('L1', 'Bangkok CBD'), ('L2', 'Free Zone Bangkok Airport'), ('L3', 'Parking Lot Besides Free Zone'), ('L4', 'Somewhere in Bangkok')], default='L2', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available', models.BooleanField(default=True)),
                ('TruckName', models.CharField(max_length=200)),
                ('Origin', models.CharField(choices=[('L1', 'Bangkok CBD'), ('L2', 'Free Zone Bangkok Airport'), ('L3', 'Parking Lot Besides Free Zone'), ('L4', 'Somewhere in Bangkok')], default='L1', max_length=2)),
                ('Cost', models.FloatField(default=0.0)),
            ],
        ),
    ]
