# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptDemoNov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
    ]
