# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptDemoNov', '0002_sysusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysusers',
            name='Type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Carrier', 'Carrier'), ('Shipper', 'Shipper')], default='Admin', max_length=7),
        ),
    ]
