# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptDemoNov', '0003_sysusers_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='Cost',
        ),
        migrations.AddField(
            model_name='truck',
            name='Animal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='Dangerous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='General',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='Perishable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='TransportationCost',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='truck',
            name='Valuable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='Origin',
            field=models.CharField(choices=[('4WOT', '4 wheel open truck'), ('4WWC', '4 wheel with cabinet'), ('4WRC', '4 wheel with refrigerated cabinet'), ('6WWC', '6 wheel with cabinet'), ('6WRC', '6 wheel with refrigerated cabinet'), ('10WC', '10 wheel with cabinet'), ('10RC', '10 wheel with refrigerated cabinet')], default='4WOT', max_length=4),
        ),
    ]
