# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptDemoNov', '0005_truck_ownername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='Origin',
            new_name='TruckType',
        ),
        migrations.AddField(
            model_name='truck',
            name='CurrentLat',
            field=models.FloatField(default=100.7518861),
        ),
        migrations.AddField(
            model_name='truck',
            name='CurrentLon',
            field=models.FloatField(default=13.7140519),
        ),
    ]
