# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptDemoNov', '0006_auto_20171119_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='DestLat',
            field=models.FloatField(default=100.7518861),
        ),
        migrations.AddField(
            model_name='truck',
            name='DestLon',
            field=models.FloatField(default=13.7140519),
        ),
    ]
