# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptDemoNov', '0007_auto_20171120_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='CurrentLat',
            field=models.FloatField(default=13.7140519),
        ),
        migrations.AlterField(
            model_name='truck',
            name='CurrentLon',
            field=models.FloatField(default=100.7518861),
        ),
        migrations.AlterField(
            model_name='truck',
            name='DestLat',
            field=models.FloatField(default=13.7140519),
        ),
        migrations.AlterField(
            model_name='truck',
            name='DestLon',
            field=models.FloatField(default=100.7518861),
        ),
    ]
